package com.feprism.entity;

import java.util.Date;

public class PageInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.pv
     *
     * @mbggenerated
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.uv
     *
     * @mbggenerated
     */
    private Integer uv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.browser_version
     *
     * @mbggenerated
     */
    private String browserVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.browser_type
     *
     * @mbggenerated
     */
    private String browserType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.browser_environment
     *
     * @mbggenerated
     */
    private String browserEnvironment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.device_resolution
     *
     * @mbggenerated
     */
    private String deviceResolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.period_time
     *
     * @mbggenerated
     */
    private String periodTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.leave_time
     *
     * @mbggenerated
     */
    private String leaveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.dns_time
     *
     * @mbggenerated
     */
    private String dnsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.bad_time
     *
     * @mbggenerated
     */
    private String badTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.first_screen_time
     *
     * @mbggenerated
     */
    private String firstScreenTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.operation_time
     *
     * @mbggenerated
     */
    private String operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.total_time
     *
     * @mbggenerated
     */
    private String totalTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.web_page_id
     *
     * @mbggenerated
     */
    private Integer webPageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.referrer
     *
     * @mbggenerated
     */
    private String referrer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    public PageInfo(Integer id, Integer pv, Integer uv, String browserVersion, String browserType, String browserEnvironment, String deviceResolution, String periodTime, String leaveTime, String dnsTime, String badTime, String firstScreenTime, String operationTime, String totalTime, Integer webPageId, String referrer, Date addTime) {
        this.id = id;
        this.pv = pv;
        this.uv = uv;
        this.browserVersion = browserVersion;
        this.browserType = browserType;
        this.browserEnvironment = browserEnvironment;
        this.deviceResolution = deviceResolution;
        this.periodTime = periodTime;
        this.leaveTime = leaveTime;
        this.dnsTime = dnsTime;
        this.badTime = badTime;
        this.firstScreenTime = firstScreenTime;
        this.operationTime = operationTime;
        this.totalTime = totalTime;
        this.webPageId = webPageId;
        this.referrer = referrer;
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    public PageInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.id
     *
     * @return the value of fe_web_page_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.id
     *
     * @param id the value for fe_web_page_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.pv
     *
     * @return the value of fe_web_page_info.pv
     *
     * @mbggenerated
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.pv
     *
     * @param pv the value for fe_web_page_info.pv
     *
     * @mbggenerated
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.uv
     *
     * @return the value of fe_web_page_info.uv
     *
     * @mbggenerated
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.uv
     *
     * @param uv the value for fe_web_page_info.uv
     *
     * @mbggenerated
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.browser_version
     *
     * @return the value of fe_web_page_info.browser_version
     *
     * @mbggenerated
     */
    public String getBrowserVersion() {
        return browserVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.browser_version
     *
     * @param browserVersion the value for fe_web_page_info.browser_version
     *
     * @mbggenerated
     */
    public void setBrowserVersion(String browserVersion) {
        this.browserVersion = browserVersion == null ? null : browserVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.browser_type
     *
     * @return the value of fe_web_page_info.browser_type
     *
     * @mbggenerated
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.browser_type
     *
     * @param browserType the value for fe_web_page_info.browser_type
     *
     * @mbggenerated
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType == null ? null : browserType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.browser_environment
     *
     * @return the value of fe_web_page_info.browser_environment
     *
     * @mbggenerated
     */
    public String getBrowserEnvironment() {
        return browserEnvironment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.browser_environment
     *
     * @param browserEnvironment the value for fe_web_page_info.browser_environment
     *
     * @mbggenerated
     */
    public void setBrowserEnvironment(String browserEnvironment) {
        this.browserEnvironment = browserEnvironment == null ? null : browserEnvironment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.device_resolution
     *
     * @return the value of fe_web_page_info.device_resolution
     *
     * @mbggenerated
     */
    public String getDeviceResolution() {
        return deviceResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.device_resolution
     *
     * @param deviceResolution the value for fe_web_page_info.device_resolution
     *
     * @mbggenerated
     */
    public void setDeviceResolution(String deviceResolution) {
        this.deviceResolution = deviceResolution == null ? null : deviceResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.period_time
     *
     * @return the value of fe_web_page_info.period_time
     *
     * @mbggenerated
     */
    public String getPeriodTime() {
        return periodTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.period_time
     *
     * @param periodTime the value for fe_web_page_info.period_time
     *
     * @mbggenerated
     */
    public void setPeriodTime(String periodTime) {
        this.periodTime = periodTime == null ? null : periodTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.leave_time
     *
     * @return the value of fe_web_page_info.leave_time
     *
     * @mbggenerated
     */
    public String getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.leave_time
     *
     * @param leaveTime the value for fe_web_page_info.leave_time
     *
     * @mbggenerated
     */
    public void setLeaveTime(String leaveTime) {
        this.leaveTime = leaveTime == null ? null : leaveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.dns_time
     *
     * @return the value of fe_web_page_info.dns_time
     *
     * @mbggenerated
     */
    public String getDnsTime() {
        return dnsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.dns_time
     *
     * @param dnsTime the value for fe_web_page_info.dns_time
     *
     * @mbggenerated
     */
    public void setDnsTime(String dnsTime) {
        this.dnsTime = dnsTime == null ? null : dnsTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.bad_time
     *
     * @return the value of fe_web_page_info.bad_time
     *
     * @mbggenerated
     */
    public String getBadTime() {
        return badTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.bad_time
     *
     * @param badTime the value for fe_web_page_info.bad_time
     *
     * @mbggenerated
     */
    public void setBadTime(String badTime) {
        this.badTime = badTime == null ? null : badTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.first_screen_time
     *
     * @return the value of fe_web_page_info.first_screen_time
     *
     * @mbggenerated
     */
    public String getFirstScreenTime() {
        return firstScreenTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.first_screen_time
     *
     * @param firstScreenTime the value for fe_web_page_info.first_screen_time
     *
     * @mbggenerated
     */
    public void setFirstScreenTime(String firstScreenTime) {
        this.firstScreenTime = firstScreenTime == null ? null : firstScreenTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.operation_time
     *
     * @return the value of fe_web_page_info.operation_time
     *
     * @mbggenerated
     */
    public String getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.operation_time
     *
     * @param operationTime the value for fe_web_page_info.operation_time
     *
     * @mbggenerated
     */
    public void setOperationTime(String operationTime) {
        this.operationTime = operationTime == null ? null : operationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.total_time
     *
     * @return the value of fe_web_page_info.total_time
     *
     * @mbggenerated
     */
    public String getTotalTime() {
        return totalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.total_time
     *
     * @param totalTime the value for fe_web_page_info.total_time
     *
     * @mbggenerated
     */
    public void setTotalTime(String totalTime) {
        this.totalTime = totalTime == null ? null : totalTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.web_page_id
     *
     * @return the value of fe_web_page_info.web_page_id
     *
     * @mbggenerated
     */
    public Integer getWebPageId() {
        return webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.web_page_id
     *
     * @param webPageId the value for fe_web_page_info.web_page_id
     *
     * @mbggenerated
     */
    public void setWebPageId(Integer webPageId) {
        this.webPageId = webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.referrer
     *
     * @return the value of fe_web_page_info.referrer
     *
     * @mbggenerated
     */
    public String getReferrer() {
        return referrer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.referrer
     *
     * @param referrer the value for fe_web_page_info.referrer
     *
     * @mbggenerated
     */
    public void setReferrer(String referrer) {
        this.referrer = referrer == null ? null : referrer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page_info.add_time
     *
     * @return the value of fe_web_page_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page_info.add_time
     *
     * @param addTime the value for fe_web_page_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}