package com.feprism.entity;

import java.util.Date;

public class ScriptInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.user_agent
     *
     * @mbggenerated
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.web_page_id
     *
     * @mbggenerated
     */
    private Integer webPageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.error_time
     *
     * @mbggenerated
     */
    private String errorTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_script_info.info
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    public ScriptInfo(Integer id, String name, String url, String userAgent, Integer webPageId, String errorTime, Date addTime, String info) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.userAgent = userAgent;
        this.webPageId = webPageId;
        this.errorTime = errorTime;
        this.addTime = addTime;
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    public ScriptInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.id
     *
     * @return the value of fe_script_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.id
     *
     * @param id the value for fe_script_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.name
     *
     * @return the value of fe_script_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.name
     *
     * @param name the value for fe_script_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.url
     *
     * @return the value of fe_script_info.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.url
     *
     * @param url the value for fe_script_info.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.user_agent
     *
     * @return the value of fe_script_info.user_agent
     *
     * @mbggenerated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.user_agent
     *
     * @param userAgent the value for fe_script_info.user_agent
     *
     * @mbggenerated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.web_page_id
     *
     * @return the value of fe_script_info.web_page_id
     *
     * @mbggenerated
     */
    public Integer getWebPageId() {
        return webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.web_page_id
     *
     * @param webPageId the value for fe_script_info.web_page_id
     *
     * @mbggenerated
     */
    public void setWebPageId(Integer webPageId) {
        this.webPageId = webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.error_time
     *
     * @return the value of fe_script_info.error_time
     *
     * @mbggenerated
     */
    public String getErrorTime() {
        return errorTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.error_time
     *
     * @param errorTime the value for fe_script_info.error_time
     *
     * @mbggenerated
     */
    public void setErrorTime(String errorTime) {
        this.errorTime = errorTime == null ? null : errorTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.add_time
     *
     * @return the value of fe_script_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.add_time
     *
     * @param addTime the value for fe_script_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_script_info.info
     *
     * @return the value of fe_script_info.info
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_script_info.info
     *
     * @param info the value for fe_script_info.info
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }
}