package com.feprism.entity;

import java.util.Date;

public class WebElement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.element_id
     *
     * @mbggenerated
     */
    private String elementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.father_element
     *
     * @mbggenerated
     */
    private String fatherElement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.custom_info
     *
     * @mbggenerated
     */
    private String customInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.click_time
     *
     * @mbggenerated
     */
    private String clickTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.click_num
     *
     * @mbggenerated
     */
    private String clickNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.web_page_id
     *
     * @mbggenerated
     */
    private Integer webPageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_element.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    public WebElement(Integer id, String name, String url, String elementId, String position, String fatherElement, String customInfo, String clickTime, String clickNum, Integer webPageId, Date addTime, String content) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.elementId = elementId;
        this.position = position;
        this.fatherElement = fatherElement;
        this.customInfo = customInfo;
        this.clickTime = clickTime;
        this.clickNum = clickNum;
        this.webPageId = webPageId;
        this.addTime = addTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    public WebElement() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.id
     *
     * @return the value of fe_web_element.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.id
     *
     * @param id the value for fe_web_element.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.name
     *
     * @return the value of fe_web_element.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.name
     *
     * @param name the value for fe_web_element.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.url
     *
     * @return the value of fe_web_element.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.url
     *
     * @param url the value for fe_web_element.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.element_id
     *
     * @return the value of fe_web_element.element_id
     *
     * @mbggenerated
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.element_id
     *
     * @param elementId the value for fe_web_element.element_id
     *
     * @mbggenerated
     */
    public void setElementId(String elementId) {
        this.elementId = elementId == null ? null : elementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.position
     *
     * @return the value of fe_web_element.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.position
     *
     * @param position the value for fe_web_element.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.father_element
     *
     * @return the value of fe_web_element.father_element
     *
     * @mbggenerated
     */
    public String getFatherElement() {
        return fatherElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.father_element
     *
     * @param fatherElement the value for fe_web_element.father_element
     *
     * @mbggenerated
     */
    public void setFatherElement(String fatherElement) {
        this.fatherElement = fatherElement == null ? null : fatherElement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.custom_info
     *
     * @return the value of fe_web_element.custom_info
     *
     * @mbggenerated
     */
    public String getCustomInfo() {
        return customInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.custom_info
     *
     * @param customInfo the value for fe_web_element.custom_info
     *
     * @mbggenerated
     */
    public void setCustomInfo(String customInfo) {
        this.customInfo = customInfo == null ? null : customInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.click_time
     *
     * @return the value of fe_web_element.click_time
     *
     * @mbggenerated
     */
    public String getClickTime() {
        return clickTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.click_time
     *
     * @param clickTime the value for fe_web_element.click_time
     *
     * @mbggenerated
     */
    public void setClickTime(String clickTime) {
        this.clickTime = clickTime == null ? null : clickTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.click_num
     *
     * @return the value of fe_web_element.click_num
     *
     * @mbggenerated
     */
    public String getClickNum() {
        return clickNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.click_num
     *
     * @param clickNum the value for fe_web_element.click_num
     *
     * @mbggenerated
     */
    public void setClickNum(String clickNum) {
        this.clickNum = clickNum == null ? null : clickNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.web_page_id
     *
     * @return the value of fe_web_element.web_page_id
     *
     * @mbggenerated
     */
    public Integer getWebPageId() {
        return webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.web_page_id
     *
     * @param webPageId the value for fe_web_element.web_page_id
     *
     * @mbggenerated
     */
    public void setWebPageId(Integer webPageId) {
        this.webPageId = webPageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.add_time
     *
     * @return the value of fe_web_element.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.add_time
     *
     * @param addTime the value for fe_web_element.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_element.content
     *
     * @return the value of fe_web_element.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_element.content
     *
     * @param content the value for fe_web_element.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}