package com.feprism.entity;

import java.util.Date;

public class WebPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.web_name
     *
     * @mbggenerated
     */
    private String webName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.web_url
     *
     * @mbggenerated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.page_id
     *
     * @mbggenerated
     */
    private String pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.pv
     *
     * @mbggenerated
     */
    private Integer pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.uv
     *
     * @mbggenerated
     */
    private Integer uv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.web_site_id
     *
     * @mbggenerated
     */
    private Integer webSiteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fe_web_page.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    public WebPage(Integer id, String webName, String webUrl, String pageId, Integer pv, Integer uv, Integer webSiteId, Date addTime) {
        this.id = id;
        this.webName = webName;
        this.webUrl = webUrl;
        this.pageId = pageId;
        this.pv = pv;
        this.uv = uv;
        this.webSiteId = webSiteId;
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    public WebPage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.id
     *
     * @return the value of fe_web_page.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.id
     *
     * @param id the value for fe_web_page.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.web_name
     *
     * @return the value of fe_web_page.web_name
     *
     * @mbggenerated
     */
    public String getWebName() {
        return webName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.web_name
     *
     * @param webName the value for fe_web_page.web_name
     *
     * @mbggenerated
     */
    public void setWebName(String webName) {
        this.webName = webName == null ? null : webName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.web_url
     *
     * @return the value of fe_web_page.web_url
     *
     * @mbggenerated
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.web_url
     *
     * @param webUrl the value for fe_web_page.web_url
     *
     * @mbggenerated
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.page_id
     *
     * @return the value of fe_web_page.page_id
     *
     * @mbggenerated
     */
    public String getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.page_id
     *
     * @param pageId the value for fe_web_page.page_id
     *
     * @mbggenerated
     */
    public void setPageId(String pageId) {
        this.pageId = pageId == null ? null : pageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.pv
     *
     * @return the value of fe_web_page.pv
     *
     * @mbggenerated
     */
    public Integer getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.pv
     *
     * @param pv the value for fe_web_page.pv
     *
     * @mbggenerated
     */
    public void setPv(Integer pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.uv
     *
     * @return the value of fe_web_page.uv
     *
     * @mbggenerated
     */
    public Integer getUv() {
        return uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.uv
     *
     * @param uv the value for fe_web_page.uv
     *
     * @mbggenerated
     */
    public void setUv(Integer uv) {
        this.uv = uv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.web_site_id
     *
     * @return the value of fe_web_page.web_site_id
     *
     * @mbggenerated
     */
    public Integer getWebSiteId() {
        return webSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.web_site_id
     *
     * @param webSiteId the value for fe_web_page.web_site_id
     *
     * @mbggenerated
     */
    public void setWebSiteId(Integer webSiteId) {
        this.webSiteId = webSiteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fe_web_page.add_time
     *
     * @return the value of fe_web_page.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fe_web_page.add_time
     *
     * @param addTime the value for fe_web_page.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}