package com.feprism.dao;

import com.feprism.entity.PageInfo;

public interface PageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    int insert(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    int insertSelective(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    PageInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PageInfo record);
}