package com.feprism.dao;

import com.feprism.entity.ScriptInfo;

public interface ScriptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int insert(ScriptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int insertSelective(ScriptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    ScriptInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScriptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ScriptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_script_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScriptInfo record);
}