package com.feprism.dao;

import com.feprism.entity.WebElement;

public interface WebElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int insert(WebElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int insertSelective(WebElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    WebElement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(WebElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_element
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebElement record);
}