package com.feprism.dao;

import com.feprism.entity.WebPage;

public interface WebPageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    int insert(WebPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    int insertSelective(WebPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    WebPage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WebPage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fe_web_page
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WebPage record);
}